# Define your personal defaults for the various configs in this section.
# Not setting a value in the actual config section will use these defaults.
# For example: the trade channel below will inherit all the configs from this defaults config.
defaults:
  channel:
    protect: false
    auto_join: false
    force: false
    console: true
    scope: server
    worlds:
      - world
      - world_nether
      - world_the_end
    range: 100
    format: '<gold>[</gold><green><channel_name></green><gold>]</gold><reset><yellow><sender_vault_prefix><sender_name><sender_vault_suffix><gray>: <gray><message>'
# You can fine tune the behaviour of the console chat in this section.
console:
  # Set the name players see when chatting from the console.
  name: Console
  # This is the channel the console will send chat messages to.
  default_channel: global
# Define your list of channels here.
channels:
  # The id of the channel must be unique across your server network.
  # Channels with the same id on different servers in the same network are considered the same.
  # The id is used in commands and permissions.
  global:
    # The display name of the channel visible in the channel tabs and messages.
    # You can reference the name in the channel format via the <channel_name> tag.
    # It is also accessible via the PlaceholderAPI under {schat.channel_name} tag.
    # default: <channel_id>
    name: Global
    # The scope of the channel defines what players receive the messages.
    # The following scopes exist:
    #   - global: the message is sent to all players on all servers
    #   - server: the message is sent to all players on the server of the sender
    #   - world:  the message is sent only to players in the defined list of worlds.
    #             Use the 'worlds' config option to define a list of worlds this channel sends messages to.
    #   - local:  the message is only sent to players inside the defined 'range' of the message sender.
    #             Use the 'range' config option to set the range of the message.
    scope: global
    # The worlds option is only applicable if the scope is set to 'world'.
    # worlds:
    # - world
    # - world_nether
    # The range option is only applicable of the scope is set to 'local'.
    # default: 100
    # range: 100
    # Set 'true' to require a permission to join the channel.
    # The permission is: 'schat.channel.<id>', e.g. 'schat.channel.global'
    # default: false
    protect: false
    # Set 'true' to prevent players from leaving the channel.
    # default: false
    force: true
    # Set 'true' to automatically let every player that has the permission join this channel.
    # This is useful for global channels that everyone should have.
    # default: false
    auto_join: true
    # Sends all chat messages in this channel to the console as well.
    # Set false to not send messages in this channel to the console.
    # default: true
    console: true
    # The formatting of the chat messages in this channel.
    # You can use the mini message format documented here: https://docs.adventure.kyori.net/minimessage#format
    # You can use the web viewer to preview how your chat will look: https://webui.adventure.kyori.net/
    # You can use any PlaceholderAPI placeholders with the {placeholder} syntax.
    # The following custom mini message placeholders are available:
    # - <channel_name>: The name of the channel (see above).
    # - <sender_vault_prefix>: The Vault prefix of the sending player. Requires Vault to work. "Bleeding" color codes in prefix and suffix currently do not work.
    # - <sender_world>: The world of the sending player.
    # - <sender_name>: The name or nick of the sending player.
    # - <sender_vault_suffix>: The Vault suffix of the sending player. Requires Vault to work. "Bleeding" color codes in prefix and suffix currently do not work.
    # - <message>: The message that is being sent.
    # default: '<gold>[</gold><green><channel_name></green><gold>]</gold><reset><yellow><sender_vault_prefix><sender_name><sender_vault_suffix><gray>: <gray><message>'
    format: '<gold>[</gold><green><channel_name></green><gold>]</gold><reset><yellow><sender_vault_prefix><sender_name><sender_vault_suffix><gray>: <gray><message>'
  trade:
    name: Trade
    auto_join: true
  team:
    # Protecting a channel requires the "schat.channel.<id>" permission to join it.
    # For the team channel this would be "schat.channel.team".
    protect: true