channels:
  global:
    name: Global
    protected: false
    format:
      prefix: '§6[§aG§6]§r'
      # alternate formatting
      # prefix: <gold>[<green>G<gold>]<reset>
      chat_color: GREEN
  trade:
    name: Trade
    format:
      prefix: '§6[§7T§6]§r'
      chat_color: GRAY
  team:
    # Protecting a channel requires the "schat.channel.<id>" permission to join it.
    # For the team channel this would be "schat.channel.team".
    protected: true