############################################################
#+--------------------------------------------------------+#
#|                                                        |#
#|                _________ .__            __             |#
#|           _____\_   ___ \|  |__ _____ _/  |_           |#
#|          /  ___/    \  \/|  |  \\__  \\   __\          |#
#|          \___ \\     \___|   Y  \/ __ \|  |            |#
#|         /____  >\______  |___|  (____  |__|            |#
#|              \/        \/     \/     \/                |#
#|                                                        |#
#|      Supercharge your Minecraft Chat Experience!       |#
#|                                                        |#
#+--------------------------------------------------------+#
############################################################


messenger: pluginmessage

channels:
  global:
    name: Global
    settings:
      protected: false
      auto_join: true
      global: true
      forced: true
      message_format: "<yellow><source.display_name></yellow><gray>: <text>"
      active_channel_format: "<green><underlined><channel.name></underlined></green>"
      inactive_channel_format: "<gray><click:run_command:'/channel join <channel.key>'><channel.name></click></gray>"
  team:
    name: Team
    settings:
      protected: true
      auto_join: true
      global: true
      forced: false
      message_format: "<#189AB4><source.display_name><gray>: <text>"