##################################################################################################
#+----------------------------------------------------------------------------------------------+#
#|                                                                                              |#
#|                                    _________ .__            __                               |#
#|                               _____\_   ___ \|  |__ _____ _/  |_                             |#
#|                              /  ___/    \  \/|  |  \\__  \\   __\                            |#
#|                              \___ \\     \___|   Y  \/ __ \|  |                              |#
#|                             /____  >\______  |___|  (____  |__|                              |#
#|                                  \/        \/     \/     \/                                  |#
#|                                                                                              |#
#|                         Supercharge your Minecraft Chat Experience!                          |#
#|                                                                                              |#
#|            WIKI:        https://schat.silthus.net/docs                                       |#
#|            DISCORD:     https://discord.gg/R4st4QxAjb                                        |#
#|            BUG REPORTS: https://github.com/sVoxelDev/sChat/issues                            |#
#|                                                                                              |#
#|     New options are not added to this file automatically. Default values are used if an      |#
#|     option cannot be found. There will always be an up-to-date config.default.yml and        |#
#|     all config values are explained in great detail on the wiki.                             |#
#+----------------------------------------------------------------------------------------------+#
##################################################################################################


#+----------------------------------------------------------------------------------------------+#
#|                                                                                              |#
#|                                        CHANNELS                                              |#
#|                                      ------------                                            |#
#| This is the main part where you configure all the chat channels on your server.              |#
#| The channels need to be configured on every server. Global channels are synced automatically.|#
#+----------------------------------------------------------------------------------------------+#
channels:

  #
  # This is the unique key of the channel.
  #
  # Every channel needs a key that must be unique across servers and
  # only contains letters, numbers, dashes (-) or underscores (_).
  #
  # The key is used when referencing the channel, e.g. in commands and permission nodes.
  #
  global:

    #
    # The friendly display name of the channel as it is shown in the GUI and messages.
    #
    name: "Global"

    #
    # Every channel can have an unlimited number of settings added and controlled by various features.
    # The settings documented here are the ones that come out of the box with sChat.
    #
    settings:

      #
      # Channels can be 'protected' to require a special permission to join.
      # The permission is composed of the channel key: 'schat.channel.<key>.join'.
      # This 'global' channel would require the 'schat.channel.global.join' permission if 'protected: true' is set.
      #
      # default: false
      #
      protected: false

      #
      # Channels with the 'auto_join' setting are automatically added to players when they join the server
      # if they have the permission to join the channel.
      #
      # default: false
      #
      auto_join: true

      #
      # 'global' channels are automatically synchronized across servers.
      # Messages sent to global channels are forwarded to all other servers in the network.
      # This requires the Bungeecord or Velocity sChat plugin. See the 'messenger' configuration below for more details.
      #
      # default: true
      #
      global: true

      #
      # A 'forced' channel cannot be left by players.
      # Combined with 'auto_join' makes for perfect server wide default channels.
      #
      # default: false
      #
      forced: true


      #+-------------------------------------------------------------------+#
      #|                                                                   |#
      #|                    CHANNEL MESSAGE FORMAT                         |#
      #|                 ----------------------------                      |#
      #|      Controls the format of messages sent to the channel.         |#
      #|                                                                   |#
      #|    https://schat.silthus.net/docs/configuration/channels#format   |#
      #|                                                                   |#
      #+-------------------------------------------------------------------+#

      format:

        #
        # The 'message_format' is used to format messages NOT sent by the viewer.
        # You can use the full power of MiniMessage (see above) and PlaceholderAPI placeholders.
        #
        message_format: "<yellow><hover:show_text:'<gray>Click to send <yellow><source_diplay_name></yellow> a message.\n<gray>Since: <aqua>%player_first_played_formatted%'><click:run_command:'/tell <source_name>'><source_display_name></click></yellow><gray>: <text>"

  team:
    name: Team
    settings:
      protected: true
      auto_join: true
      global: true
      forced: false
      format:
        message_format: "<#189AB4><source_display_name><gray>: <text>"

#+----------------------------------------------------------------------------------------------+#
#|                                                                                              |#
#|                                   VIEW CONFIGURATION                                         |#
#|                                      ------------                                            |#
#|                      Configure the behaviour of the view here.                               |#
#|              https://schat.silthus.net/docs/configuration/reference#view                     |#
#|                                                                                              |#
#+----------------------------------------------------------------------------------------------+#
view:

#
# Controls how global messages are relayed to the other servers.
# Read the wiki before modifying this!
#
# Wiki: https://schat.silthus.net/docs/configuration/reference#messenger
#
messenger: pluginmessage

#
# Change how some messages are presented to the user.
# Available modes are:
#   - NONE
#   - ACTION_BAR
#   - TEXT
#
message_modes:
  JOINED_CHANNEL: ACTION_BAR
  JOIN_CHANNEL_ERROR: TEXT
  LEFT_CHANNEL: ACTION_BAR
  LEAVE_CHANNEL_ERROR: TEXT
