main: net.silthus.schat.bukkit.BukkitLoader
name: sChat
version: ${version}
author: Silthus
api-version: 1.13
load: STARTUP
depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI
  - WorldGuard
permissions:
  schat.player:
    description: Contains all basic player permissions for using sChat.
    default: "true"
    children:
      schat.player.channel: true
      schat.player.channel.join: true
      schat.player.channel.leave: true
      schat.player.channel.quickmessage: true
      schat.player.directmessage: true
  schat.admin:
    description: Contains all admin permissions for sChat.
    default: op
    children:
      schat.admin.reload: true
      schat.admin.broadcast: true
      schat.message.select: true
      schat.message.delete: true
      schat.nickname.set: true
      schat.nickname.set.blocked: true
      schat.nickname.set.others: true