messenger: mock
channels:
  test:
    name: Test
    settings:
      protected: true
      auto_join: true
      format:
        message: "<yellow><source.display_name><gray>: <text>"
        active_channel:
          color: red
          decoration: underlined
  global:
    name: Global
    settings:
      global: true
  invalid: null