############################################################
#+--------------------------------------------------------+#
#|                                                        |#
#|                _________ .__            __             |#
#|           _____\_   ___ \|  |__ _____ _/  |_           |#
#|          /  ___/    \  \/|  |  \\__  \\   __\          |#
#|          \___ \\     \___|   Y  \/ __ \|  |            |#
#|         /____  >\______  |___|  (____  |__|            |#
#|              \/        \/     \/     \/                |#
#|                                                        |#
#|     Supercharge your Minecraft Chat Experience!        |#
#|                                                        |#
#+--------------------------------------------------------+#
############################################################
messenger: pluginmessage
channels:
  global:
    name: Global
    settings:
      protected: false
      auto_join: true
      global: true
      format:
        message: "<yellow><source.display_name><gray>: <text>"
        active_channel:
          color: green
          decoration: underlined
  team:
    name: Team
    settings:
      protected: true
      auto_join: true
      global: true
      format:
        message: "<blue><source.display_name><gray>: <text>"